package model.am.client;

import model.am.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 28 17:37:34 CET 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }

    public String currentQueue(Integer masterId, Integer pumpaId) {
        Object _ret = this.riInvokeExportedMethod(this, "currentQueue", new String[] {
                                                  "java.lang.Integer", "java.lang.Integer" }, new Object[] {
                                                  masterId, pumpaId });
        return (String) _ret;
    }

    public String insertDolazak(Integer masterId, Integer pumpaId) {
        Object _ret = this.riInvokeExportedMethod(this, "insertDolazak", new String[] {
                                                  "java.lang.Integer", "java.lang.Integer" }, new Object[] {
                                                  masterId, pumpaId });
        return (String) _ret;
    }

    public String insertKrajPunjenja(Integer masterId, Integer pumpaId) {
        Object _ret = this.riInvokeExportedMethod(this, "insertKrajPunjenja", new String[] {
                                                  "java.lang.Integer", "java.lang.Integer" }, new Object[] {
                                                  masterId, pumpaId });
        return (String) _ret;
    }

    public String insertOdlazak(Integer masterId, Integer pumpaId) {
        Object _ret = this.riInvokeExportedMethod(this, "insertOdlazak", new String[] {
                                                  "java.lang.Integer", "java.lang.Integer" }, new Object[] {
                                                  masterId, pumpaId });
        return (String) _ret;
    }
}

