package model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 28 17:37:34 CET 2015
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    String currentQueue(Integer masterId, Integer pumpaId);

    String insertDolazak(Integer masterId, Integer pumpaId);

    String insertKrajPunjenja(Integer masterId, Integer pumpaId);

    String insertOdlazak(Integer masterId, Integer pumpaId);
}

